[package]
name = "rust-zero"
version = "0.1.0"
authors = ["Yuxi Wang <yuxi.wangcd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
